resolver: lts-8.3

packages:
- '.'
- '../brisk'
- '../brisk-prelude'
## - location:
##     git:    https://github.com/abakst/Brisk
##     commit: f7d11a59646de7f558c069d2e93f32af65d3f22c
##   extra-dep: true
##- location:
##    git:    https://github.com/abakst/brisk-prelude
##    commit: 3bc935437990521f85a32fd7fb6af9f6fa446d2d
##  extra-dep: true

extra-deps:
- distributed-process-0.6.6
- distributed-process-async-0.2.3
- distributed-process-extras-0.2.1.2
- distributed-process-client-server-0.1.3.2
- concurrent-extra-0.7.0.10

flags: {}

extra-package-dbs: []

